spring.application.name=inventory-system-remastered

spring.datasource.url=jdbc:postgresql://localhost:5432/inventory
spring.datasource.username=postgres
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
